<?php

/**
 * @file
 * Contains grid_layouts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function grid_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the grid_layouts module.
    case 'help.page.grid_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Compose grid aware layouts.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function grid_layouts_theme() {
  $theme = [];

  return $theme;
}
